# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.5.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: neil.campbell@makerx.com.au
author_name: Neil Campbell
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: simple-python

