name: 'Create release'
description: 'Create a new release'
inputs:
  github-token:
    description: 'The GitHub token'
    required: true
  production-release:
    description: 'Is production release?'
    required: true
  node-version:
    description: 'The Node version'
    required: true
    default: '20'

runs:
  using: 'composite'
  steps:
    # run npm ci preventing script access to npm auth token
    - name: Install dependencies
      run: npm ci --ignore-scripts
      shell: bash

    - name: Create release ${{ inputs.production-release == 'true' && '' || 'beta' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: npm run create-release -- ${{ inputs.production-release == 'true' && '--branches main' || '' }}
      shell: bash

    - name: Publish release
      if: ${{ inputs.production_release == 'true' }}
      run: npx vsce publish --packagePath $(find . -iname '*.vsix')
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      shell: bash
