name: 'Build and Test'
description: 'Build and test the extensions'

runs:
  using: 'composite'
  steps:
    # run npm ci preventing script access to npm auth token
    - name: Install dependencies
      run: npm ci --ignore-scripts
      shell: bash

    - run: npm run lint
      shell: bash

    - run: npm run audit
      shell: bash

    - run: npm run build
      shell: bash

    - name: Run tests (Linux)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
      shell: bash

    - name: Run tests (Non-Linux)
      run: npm test
      if: runner.os != 'Linux'
      shell: bash
