name: 'Build and Test'
description: 'Build and test an VSCode extension'
inputs:
  working-directory:
    description: 'The working directory to run commands in'
    required: true

runs:
  using: 'composite'
  steps:
    # run npm ci preventing script access to npm auth token
    - name: Install dependencies
      run: npm ci --ignore-scripts
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - run: npm run audit
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - run: npm run lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    # TODO: NC - Temporarily disabled
    # - name: Run tests (Linux)
    #   run: xvfb-run -a npm test
    #   if: runner.os == 'Linux'
    #   working-directory: ${{ inputs.working-directory }}
    #   shell: bash

    # - name: Run tests (Non-Linux)
    #   run: npm test
    #   if: runner.os != 'Linux'
    #   working-directory: ${{ inputs.working-directory }}
    #   shell: bash

    # TODO: NC - Temporarily here
    - name: Get next version (dry run)
      id: get-next-version
      run: npm run semantic-test -w
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
